/**
 * Banco de pictogramas para o jogo da memória em mandarim
 * Estrutura de dados conforme requisitos
 */

// Banco inicial com 50 pictogramas básicos conforme requisitos
const pictogramsBank = [
  // Números
  { id: 1, character: "一", pinyin: "yī", meaning: "um", category: "numeros" },
  { id: 2, character: "二", pinyin: "èr", meaning: "dois", category: "numeros" },
  { id: 3, character: "三", pinyin: "sān", meaning: "três", category: "numeros" },
  { id: 4, character: "四", pinyin: "sì", meaning: "quatro", category: "numeros" },
  { id: 5, character: "五", pinyin: "wǔ", meaning: "cinco", category: "numeros" },
  { id: 6, character: "六", pinyin: "liù", meaning: "seis", category: "numeros" },
  { id: 7, character: "七", pinyin: "qī", meaning: "sete", category: "numeros" },
  { id: 8, character: "八", pinyin: "bā", meaning: "oito", category: "numeros" },
  { id: 9, character: "九", pinyin: "jiǔ", meaning: "nove", category: "numeros" },
  { id: 10, character: "十", pinyin: "shí", meaning: "dez", category: "numeros" },
  { id: 11, character: "百", pinyin: "bǎi", meaning: "cem", category: "numeros" },
  { id: 12, character: "千", pinyin: "qiān", meaning: "mil", category: "numeros" },
  { id: 13, character: "万", pinyin: "wàn", meaning: "dez mil", category: "numeros" },
  { id: 14, character: "零", pinyin: "líng", meaning: "zero", category: "numeros" },
  { id: 15, character: "双", pinyin: "shuāng", meaning: "par", category: "numeros" },
  { id: 16, character: "半", pinyin: "bàn", meaning: "meio", category: "numeros" },
  { id: 17, character: "第", pinyin: "dì", meaning: "ordinal", category: "numeros" },
  { id: 18, character: "全", pinyin: "quán", meaning: "todo", category: "numeros" },
  { id: 19, character: "多", pinyin: "duō", meaning: "muito", category: "numeros" },
  { id: 20, character: "少", pinyin: "shǎo", meaning: "pouco", category: "numeros" },
  { id: 21, character: "人", pinyin: "rén", meaning: "pessoa", category: "familia" },
  { id: 22, character: "男", pinyin: "nán", meaning: "homem", category: "familia" },
  { id: 23, character: "女", pinyin: "nǚ", meaning: "mulher", category: "familia" },
  { id: 24, character: "子", pinyin: "zǐ", meaning: "filho", category: "familia" },
  { id: 25, character: "父", pinyin: "fù", meaning: "pai", category: "familia" },
  { id: 26, character: "母", pinyin: "mǔ", meaning: "mãe", category: "familia" },
  { id: 27, character: "兄", pinyin: "xiōng", meaning: "irmão mais velho", category: "familia" },
  { id: 28, character: "弟", pinyin: "dì", meaning: "irmão mais novo", category: "familia" },
  { id: 29, character: "姐", pinyin: "jiě", meaning: "irmã mais velha", category: "familia" },
  { id: 30, character: "妹", pinyin: "mèi", meaning: "irmã mais nova", category: "familia" },
  { id: 31, character: "夫", pinyin: "fū", meaning: "marido", category: "familia" },
  { id: 32, character: "妻", pinyin: "qī", meaning: "esposa", category: "familia" },
  { id: 33, character: "爸", pinyin: "bà", meaning: "papai", category: "familia" },
  { id: 34, character: "妈", pinyin: "mā", meaning: "mamãe", category: "familia" },
  { id: 35, character: "祖父", pinyin: "zǔfù", meaning: "avô", category: "familia" },
  { id: 36, character: "祖母", pinyin: "zǔmǔ", meaning: "avó", category: "familia" },
  { id: 37, character: "叔", pinyin: "shū", meaning: "tio paterno", category: "familia" },
  { id: 38, character: "舅", pinyin: "jiù", meaning: "tio materno", category: "familia" },
  { id: 39, character: "姑", pinyin: "gū", meaning: "tia paterna", category: "familia" },
  { id: 40, character: "姨", pinyin: "yí", meaning: "tia materna", category: "familia" },
  { id: 41, character: "水", pinyin: "shuǐ", meaning: "água", category: "natureza" },
  { id: 42, character: "火", pinyin: "huǒ", meaning: "fogo", category: "natureza" },
  { id: 43, character: "木", pinyin: "mù", meaning: "madeira", category: "natureza" },
  { id: 44, character: "土", pinyin: "tǔ", meaning: "terra", category: "natureza" },
  { id: 45, character: "山", pinyin: "shān", meaning: "montanha", category: "natureza" },
  { id: 46, character: "日", pinyin: "rì", meaning: "sol", category: "natureza" },
  { id: 47, character: "月", pinyin: "yuè", meaning: "lua", category: "natureza" },
  { id: 48, character: "星", pinyin: "xīng", meaning: "estrela", category: "natureza" },
  { id: 49, character: "天", pinyin: "tiān", meaning: "céu", category: "natureza" },
  { id: 50, character: "地", pinyin: "dì", meaning: "solo", category: "natureza" },
  { id: 51, character: "风", pinyin: "fēng", meaning: "vento", category: "natureza" },
  { id: 52, character: "雨", pinyin: "yǔ", meaning: "chuva", category: "natureza" },
  { id: 53, character: "雷", pinyin: "léi", meaning: "trovão", category: "natureza" },
  { id: 54, character: "雪", pinyin: "xuě", meaning: "neve", category: "natureza" },
  { id: 55, character: "云", pinyin: "yún", meaning: "nuvem", category: "natureza" },
  { id: 56, character: "花", pinyin: "huā", meaning: "flor", category: "natureza" },
  { id: 57, character: "草", pinyin: "cǎo", meaning: "grama", category: "natureza" },
  { id: 58, character: "海", pinyin: "hǎi", meaning: "mar", category: "natureza" },
  { id: 59, character: "河", pinyin: "hé", meaning: "rio", category: "natureza" },
  { id: 60, character: "湖", pinyin: "hú", meaning: "lago", category: "natureza" },
  { id: 61, character: "猫", pinyin: "māo", meaning: "gato", category: "animais" },
  { id: 62, character: "狗", pinyin: "gǒu", meaning: "cachorro", category: "animais" },
  { id: 63, character: "鸟", pinyin: "niǎo", meaning: "pássaro", category: "animais" },
  { id: 64, character: "鱼", pinyin: "yú", meaning: "peixe", category: "animais" },
  { id: 65, character: "马", pinyin: "mǎ", meaning: "cavalo", category: "animais" },
  { id: 66, character: "牛", pinyin: "niú", meaning: "vaca", category: "animais" },
  { id: 67, character: "羊", pinyin: "yáng", meaning: "ovelha", category: "animais" },
  { id: 68, character: "鸡", pinyin: "jī", meaning: "galinha", category: "animais" },
  { id: 69, character: "龙", pinyin: "lóng", meaning: "dragão", category: "animais" },
  { id: 70, character: "虎", pinyin: "hǔ", meaning: "tigre", category: "animais" },
  { id: 71, character: "兔", pinyin: "tù", meaning: "coelho", category: "animais" },
  { id: 72, character: "象", pinyin: "xiàng", meaning: "elefante", category: "animais" },
  { id: 73, character: "熊", pinyin: "xióng", meaning: "urso", category: "animais" },
  { id: 74, character: "蛇", pinyin: "shé", meaning: "cobra", category: "animais" },
  { id: 75, character: "鼠", pinyin: "shǔ", meaning: "rato", category: "animais" },
  { id: 76, character: "猪", pinyin: "zhū", meaning: "porco", category: "animais" },
  { id: 77, character: "鹿", pinyin: "lù", meaning: "veado", category: "animais" },
  { id: 78, character: "狼", pinyin: "láng", meaning: "lobo", category: "animais" },
  { id: 79, character: "猴", pinyin: "hóu", meaning: "macaco", category: "animais" },
  { id: 80, character: "狐狸", pinyin: "húlí", meaning: "raposa", category: "animais" },
  { id: 81, character: "大", pinyin: "dà", meaning: "grande", category: "basicos" },
  { id: 82, character: "小", pinyin: "xiǎo", meaning: "pequeno", category: "basicos" },
  { id: 83, character: "上", pinyin: "shàng", meaning: "em cima", category: "basicos" },
  { id: 84, character: "下", pinyin: "xià", meaning: "embaixo", category: "basicos" },
  { id: 85, character: "左", pinyin: "zuǒ", meaning: "esquerda", category: "basicos" },
  { id: 86, character: "右", pinyin: "yòu", meaning: "direita", category: "basicos" },
  { id: 87, character: "好", pinyin: "hǎo", meaning: "bom", category: "basicos" },
  { id: 88, character: "坏", pinyin: "huài", meaning: "ruim", category: "basicos" },
  { id: 89, character: "新", pinyin: "xīn", meaning: "novo", category: "basicos" },
  { id: 90, character: "老", pinyin: "lǎo", meaning: "velho", category: "basicos" },
  { id: 91, character: "快", pinyin: "kuài", meaning: "rápido", category: "basicos" },
  { id: 92, character: "慢", pinyin: "màn", meaning: "devagar", category: "basicos" },
  { id: 93, character: "高", pinyin: "gāo", meaning: "alto", category: "basicos" },
  { id: 94, character: "低", pinyin: "dī", meaning: "baixo", category: "basicos" },
  { id: 95, character: "多", pinyin: "duō", meaning: "muito", category: "basicos" },
  { id: 96, character: "少", pinyin: "shǎo", meaning: "pouco", category: "basicos" },
  { id: 97, character: "前", pinyin: "qián", meaning: "frente", category: "basicos" },
  { id: 98, character: "后", pinyin: "hòu", meaning: "atrás", category: "basicos" },
  { id: 99, character: "中", pinyin: "zhōng", meaning: "meio", category: "basicos" },
  { id: 100, character: "远", pinyin: "yuǎn", meaning: "longe", category: "basicos" }
];
